GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/62a2fb8c2fb8267565f56240




###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Vuyo Dila",
    "subscribedToChannel": "SSVK TV"
}


###

DELETE http://localhost:3000/subscribers/62a303772fb8267565f56247


###
PATCH  http://localhost:3000/subscribers/62a32f30156f777a91629d1f
Content-Type: application/json

{
    "name": "Random Surname ",
    "subscribedToChannel": "Youtube TV"
}
